[build]
  base = "Exhibition-Curator"
  publish = "Exhibition-Curator/dist"  # Adjust this based on where the final build files are output
  command = "npm run build"  # or any other build command you use
